#!/usr/bin/env python3
"""
workers/lean_search.py — Lean/Mathlib search worker

Reads {"conjecture": "..."} JSON from stdin.
Searches Mathlib for related theorems via LeanExplore.
Writes result JSON to stdout (no lean4web_link — generated by orchestrator after Judge).

Usage:
    echo '{"conjecture": "n squared plus n is even"}' | python workers/lean_search.py
"""

import json
import sys

from dotenv import load_dotenv

load_dotenv()


def _search_mathlib(query: str, top_k: int = 3) -> tuple[list[dict], str | None]:
    """Search Mathlib using LeanExplore. Returns (matches, error_or_None)."""
    try:
        from leanexplore import Client
    except ImportError:
        return [], "lean-explore not installed"

    try:
        client = Client()
        results = client.search(query, n=top_k)
        matches = []
        for r in results:
            matches.append({
                "name": getattr(r, "name", str(r)),
                "statement": getattr(r, "statement", ""),
                "docstring": getattr(r, "docstring", "") or "",
            })
        return matches, None
    except Exception as e:
        return [], str(e)


def main():
    raw = sys.stdin.read().strip()
    try:
        data = json.loads(raw)
    except json.JSONDecodeError as e:
        json.dump({"mathlib_matches": [], "mathlib_found": False, "error": f"Invalid JSON input: {e}"}, sys.stdout)
        sys.exit(1)

    conjecture = data.get("conjecture", "")
    matches, error = _search_mathlib(conjecture)

    json.dump({
        "mathlib_matches": matches,
        "mathlib_found": len(matches) > 0,
        "error": error,
    }, sys.stdout, ensure_ascii=False)


if __name__ == "__main__":
    main()
